{% set name = "safetensors" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2dbd34554ed3b99435a0e84df077108f5334c8336b5ed9cb8b6b98f7b10da2f6

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - setuptools
    - setuptools-rust
    - pip
    - wheel
  run:
    - python

test:
  imports:
    - safetensors
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/huggingface/safetensors
  dev_url: https://github.com/huggingface/safetensors
  doc_url: https://huggingface.co/docs/safetensors/index
  summary: Fast and Safe Tensor serialization
  description: |
    Simple, safe way to store and distribute tensors.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
