{% set name = "safetensors" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/safetensors-{{ version }}.tar.gz
  sha256: 5be8b2fccdc6aec84c9d6732180575fe1ba3afc559cbe96e2301eacc45c5b9a6

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - setuptools-rust
    - pip
  run:
    - python

test:
  imports:
    - safetensors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/huggingface/safetensors
  summary: Fast and Safe Tensor serialization
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
