{% set name = "safetensors" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b985953c3cf11e942eac4317ef3db3da713e274109cf7cfb6076d877054f013e

build:
  number: 0
  skip: True  # [py<38 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - wheel
    - maturin 1.3.0
  run:
    - python
  run_constrained:
    - numpy >= 1.21.6
    - tensorflow >= 2.11
    - jax >= 0.3.25
    - jaxlib >= 0.3.25
    - flax >= 0.6.3

test:
# Skip tests on ppc64le/python 3.11; missing pytorch.
{% if not (ppc64le and py>310) %}
  source_files:
    # Excluded test modules:
    # test_flax_comparison.py: Missing flax on defaults
    # test_paddle_comparison.py: Missing paddlepaddle on defaults
    # test_tf_comparison.py: Adding tensorflow causes pip check to fail
    - bindings/python/tests/data
    - bindings/python/tests/test_pt_comparison.py
    - bindings/python/tests/test_pt_model.py
    - bindings/python/tests/test_simple.py
{% endif %}
  imports:
    - safetensors
  requires:
    - pip
{% if not (ppc64le and py>310) %}
    - numpy
    - h5py >= 3.7.0
    - huggingface_hub >= 0.12.1
    - setuptools-rust >= 1.5.2
    - pytest >= 7.2.0
    - pytest-benchmark >= 4.0.0
    - hypothesis >= 6.70.2
    - pytorch >= 1.10
{% endif %}
  commands:
    - pip check
    - cd bindings/python  # [not (ppc64le and py>310)]
    - pytest tests  # [not (ppc64le and py>310)]

about:
  home: https://github.com/huggingface/safetensors
  dev_url: https://github.com/huggingface/safetensors
  doc_url: https://huggingface.co/docs/safetensors/index
  summary: Fast and Safe Tensor serialization
  description: |
    Simple, safe way to store and distribute tensors.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
