{% set name = "safetensors" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43ff2aa0e6fa2dc3ea5524ac7ad93a9839256b8703761e76e2d0b2a3fa4f15d9

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - maturin >=1.0,<2.0
  run:
    - python
  run_constrained:
    - numpy >=1.21.6
    - tensorflow >=2.11.0
    - jax >=0.3.25
    - jaxlib >=0.3.25
    - pytorch >=1.10
    - mlx >=0.0.9
    - paddlepaddle >=2.4.1

# E   ModuleNotFoundError: No module named 'flax'
{% set ignore_tests = " --ignore=bindings/python/tests/test_flax_comparison.py" %}
# E   FileNotFoundError: [Errno 2] Unable to synchronously create file (unable to open file: name = './tests/data/tf_load.h5', ...
{% set ignore_tests = ignore_tests + " --ignore=bindings/python/tests/test_pt_comparison.py" %}
{% set ignore_tests = ignore_tests + " --ignore=bindings/python/tests/test_tf_comparison.py" %}

test:
  source_files:
    - bindings/python/tests
  imports:
    - safetensors
  requires:
    - pip
    - pytest >=7.2.0
    - pytorch >=1.10
    - jax >=0.3.25
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v bindings/python/tests {{ ignore_tests }}

about:
  home: https://github.com/huggingface/safetensors
  dev_url: https://github.com/huggingface/safetensors
  doc_url: https://huggingface.co/docs/safetensors/index
  summary: Fast and Safe Tensor serialization
  description: |
    Simple, safe way to store and distribute tensors.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for vllm
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - jan-janssen
